### ISSUE TITLE
Solid version of 507391-OSNN-1 seems broken

### ISSUE THREAD

**Issue by lucaswerkmeister** [wearebeautiful/wearebeautiful-models#1]
The solid version of the 507391-OSNN-1 model looks broken on Wikimedia Commons: https://commons.wikimedia.org/wiki/File:We_Are_Beautiful_%E2%80%93_507391-OSNN-1_%E2%80%93_solid.stl

![3D model view with only a few thin blobs floating in a black void](https://user-images.githubusercontent.com/2346599/96353900-c1775f80-10d0-11eb-942c-5dd1aa39f4d3.png)

On the [We Are Beautiful model page](https://wearebeautiful.info/model/507391-OSNN), you can only see the surface (which looks fine), but I think this is a bug in the source data, not in the Wikimedia Commons upload/import – the solid file is also suspiciously small:

![solid.stl, 68 KB download size; surface.stl, 1 MB download size](https://user-images.githubusercontent.com/2346599/96353913-dce26a80-10d0-11eb-8452-123cb0d499c7.png)

**Comment by mayhem** [comment]
That is clearly our problem -- I will re-generate the model and re-upload later this week.

**Comment by lucaswerkmeister** [comment]
A couple of updates from my side:

- As far as I can tell, the solid version is still broken; unlike what I wrote above, it *is* now possible to view it on the website: https://hiddenbeauty.ch/model/507391-OSNN/solid – and it looks just like on Commons there, so the breakage is indeed in the model itself.
- Someone else noticed the breakage on Wikimedia Commons and [nominated the file for deletion there](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:We_Are_Beautiful_%E2%80%93_507391-OSNN-1_%E2%80%93_solid.stl), so if you’re still able to, it would be amazing if you could generate a fixed version. (Evidently, someone is looking at these files, otherwise they wouldn’t have noticed it ^^)
- I see the project has rebranded in the meantime; would you like me to move the issue to a new GitHub repository? (Probably to https://github.com/hidden-beauty/hiddenbeauty-models/issues?)

(I’m aware the project is also terminated; if you don’t want to respond, that’s of course completely fine too. In any case, thank you for all the work you’ve done here!)

**Comment by mayhem** [comment]
Hi!

Yes, the project is concluded and I dont even have the source files anymore, so I can't fix it. Lets just get that file removed and be done with it.
